services:
  - type: web
    name: cdarch-php-backup
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 10000
